const dummyData = [
   {
      user_id: 1,
      owner_id: 10,
      name: 'Astra',
      facility: 'AC, Wifi',
      location: 'Jl. Jenderal Sudirman No.Kav.5-6, RT.10/RW.6, Jakarta Pusat, DKI Jakarta',
      city: 'Jakarta Pusat',
      provinc: 'DKI Jakarta',
      size: '100 x 100',
      accommodate: 25,
      description: 'Tempat yang nyaman untuk melakukan event',
      price: 10000000,
      category: 'Event',
   },
   {
      user_id: 2,
      owner_id: 8,
      name: 'Yafurni',
      facility: 'AC, Wifi',
      location: 'Jl. Iskandar Muda No.7, Petisah Hulu, Medan, Sumatera Utara',
      city: 'Medan',
      provinc: 'Sumatera Utara',
      size: '100 x 100',
      accommodate: 10,
      description: '-',
      price: 6000000,
      category: 'Meeting',
   },
   {
      user_id: 3,
      owner_id: 12,
      name: 'Expo Center',
      facility: 'AC, Parking, Stage',
      location: 'Jl. Gatot Subroto No.10, Senayan, Jakarta Selatan, DKI Jakarta',
      city: 'Jakarta Selatan',
      provinc: 'DKI Jakarta',
      size: '150 x 150',
      accommodate: 50,
      description: 'Ideal for exhibitions and large events',
      price: 15000000,
      category: 'Exhibition',
   },
   {
      user_id: 4,
      owner_id: 10,
      name: 'Astra',
      facility: 'AC, Wifi',
      location: 'Jl. Jenderal Sudirman No.Kav.5-6, RT.10/RW.6, Jakarta Pusat, DKI Jakarta',
      city: 'Jakarta Pusat',
      provinc: 'DKI Jakarta',
      size: '100 x 100',
      accommodate: 25,
      description: 'Tempat yang nyaman untuk melakukan event',
      price: 10000000,
      category: 'Event',
   },
   {
      user_id: 5,
      owner_id: 8,
      name: 'Yafurni',
      facility: 'AC, Wifi',
      location: 'Jl. Iskandar Muda No.7, Petisah Hulu, Medan, Sumatera Utara',
      city: 'Medan',
      provinc: 'Sumatera Utara',
      size: '100 x 100',
      accommodate: 10,
      description: '-',
      price: 6000000,
      category: 'Meeting',
   },
   {
      user_id: 6,
      owner_id: 12,
      name: 'Expo Center',
      facility: 'AC, Parking, Stage',
      location: 'Jl. Gatot Subroto No.10, Senayan, Jakarta Selatan, DKI Jakarta',
      city: 'Jakarta Selatan',
      provinc: 'DKI Jakarta',
      size: '150 x 150',
      accommodate: 50,
      description: 'Ideal for exhibitions and large events',
      price: 15000000,
      category: 'Exhibition',
   },
   {
      user_id: 7,
      owner_id: 15,
      name: 'Tech Hub',
      facility: 'High-speed Internet, Projectors',
      location: 'Silicon Valley Street, Palo Alto, California, USA',
      city: 'Palo Alto',
      provinc: 'California',
      size: '80 x 80',
      accommodate: 30,
      description: 'Perfect for tech-related conferences and meetups',
      price: 12000000,
      category: 'Conference',
   },
   {
      user_id: 8,
      owner_id: 14,
      name: 'Garden Oasis',
      facility: 'Outdoor Space, Catering',
      location: '123 Green Lane, Natureville, Garden State',
      city: 'Natureville',
      provinc: 'Garden State',
      size: '200 x 200',
      accommodate: 100,
      description: 'Beautiful garden setting for weddings and outdoor events',
      price: 20000000,
      category: 'Wedding',
   },
];

export default dummyData;